towns_and_cities = [
  'New York City',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'Fort Worth',
  'Columbus',
  'San Francisco',
  'Charlotte',
  'Indianapolis',
  'Seattle',
  'Denver',
  'Washington, D.C.',
  'Boston',
  'Nashville',
  'El Paso',
  'Detroit',
  'Memphis',
  'Portland',
  'Oklahoma City',
  'Las Vegas',
  'Louisville',
  'Baltimore',
  'Milwaukee',
  'Albuquerque',
  'Tucson',
  'Fresno',
  'Sacramento',
  'Mesa',
  'Atlanta',
  'Kansas City',
  'Colorado Springs',
  'Miami',
  'Raleigh',
  'Omaha',
  'Long Beach',
  'Virginia Beach',
  'Oakland',
  'Minneapolis',
  'Tulsa',
  'Wichita',
  'New Orleans',
  'Arlington',
  'Tampa',
  'Aurora',
  'Santa Ana',
  'St. Louis',
  'Pittsburgh',
  'Corpus Christi',
  'Riverside',
  'Cincinnati',
  'Lexington',
  'Anchorage',
  'Stockton',
  'Toledo',
  'Saint Paul',
  'Newark',
  'Greensboro',
  'Buffalo',
  'Plano',
  'Lincoln',
  'Henderson',
  'Fort Wayne',
  'Jersey City',
  'St. Petersburg',
  'Chula Vista',
  'Norfolk',
  'Orlando',
  'Chandler',
  'Laredo',
  'Madison',
  'Winston-Salem',
  'Lubbock',
  'Baton Rouge',
  'Durham',
  'Garland',
  'Glendale',
  'Reno',
  'Hialeah',
  'Chesapeake',
  'Scottsdale',
  'North Las Vegas',
  'Irving',
  'Fremont',
  'Irvine',
  'Birmingham',
  'Rochester',
  'San Bernardino',
  'Spokane',
  'Gilbert',
  'Arlington',
  'Montgomery',
  'Boise',
  'Richmond',
  'Des Moines',
  'Modesto',
  'Fayetteville',
  'Shreveport',
  'Akron',
  'Augusta',
  'Grand Rapids',
  'Huntsville',
  'Salt Lake City',
  'Mobile',
  'Tallahassee',
  'Grand Prairie',
  'Overland Park',
  'Knoxville',
  'Port St. Lucie',
  'Worcester',
  'Brownsville',
  'Tempe',
  'Santa Clarita',
  'Newport News',
  'Cape Coral',
  'Providence',
  'Fort Lauderdale',
  'Chattanooga',
  'Rancho Cucamonga',
  'Oceanside',
  'Santa Rosa',
  'Garden Grove',
  'Vancouver',
  'Sioux Falls',
  'Ontario',
  'McKinney',
  'Elk Grove',
  'Jackson',
  'Pembroke Pines',
  'Salem',
  'Springfield'
]